name: network_wrapper
description: A wrapper for network requests.
version: 1.0.5
homepage: https://github.com/vicajilau/network_service

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  flutter_lints: ">=3.0.1 <6.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
